### ISSUE TITLE
Bonus Section is missing tests

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-students/pokemon-scraper-v-000#225]
The bonus section was removed in this commit: https://github.com/learn-co-students/pokemon-scraper-v-000/commit/80a1a86f404c97bfdbac7478d2c78302d6de894a

Bonus language was added back in the readme in May (which references pending tests): https://github.com/learn-co-students/pokemon-scraper-v-000/commit/a0ecb14b6ec1efadc86a9ea1d8dced928d12e691

But the bonus tests were never added back.

@PeterBell

**Comment by PeterBell** [comment]
Hmmm, @pletcher ?

**Comment by pletcher** [comment]
Fixed, thanks. https://github.com/learn-co-curriculum/pokemon-scraper/commit/2520ef69d62222845425944d2c6e0c8c5d7058f2
